version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment: 
      MYSQL_ROOT_PASSWORD: tlp
      MYSQL_DATABASE: tlp
      MYSQL_USER: tlp
      MYSQL_PASSWORD: tlp
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: tlp
      PMA_PASSWORD: tlp
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./src:/var/www/src
    environment:
      DB_HOST: db
      DB_DATABASE: tlp
      DB_USERNAME: tlp
      DB_PASSWORD: tlp
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "chown -R www-data:www-data /var/www/src/storage /var/www/src/bootstrap/cache &&
             chmod -R 775 /var/www/src/storage /var/www/src/bootstrap/cache &&
             php-fpm"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/src
    depends_on:
      - laravel
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
